#!/usr/bin/env python
from msmb.config.app import (MSMBuilderApp, RootApplication,
        collect_subcommands)
# import all of the apps
from msmb.commands import *

def main():
    # register lall of the apps as subcommands
    app = RootApplication.instance()
    RootApplication.subcommands = collect_subcommands()
    app.initialize()
    app.start()

if __name__ == '__main__':
    main()
    
   